export const VALIDATION_LIMITS = {
  MIN_WORDS_BG: 50,
  MAX_CHARS_BG: 100000,
  MAX_CHARS_INTERACTION: 5000,
  MAX_CHARS_FEEDBACK: 2000,
  MAX_CHARS_OBJECTIVE: 1000,
  MIN_CHARS_FEEDBACK: 10,
  MIN_CHARS_PASSWORD: 6,
} as const;
