// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfpduruccpbfyrjfwnso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmcGR1cnVjY3BiZnlyamZ3bnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDgzNTIsImV4cCI6MjA2MTY4NDM1Mn0.V5GSlIz7gKsAQLdnQ2OdH1ScHy2DgG6DM4i-IEse4m4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);