// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exbzektbhynykyschqso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4Ynpla3RiaHlueWt5c2NocXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Mzk2NDksImV4cCI6MjA2NDExNTY0OX0.yN9C7USIeelvdfTs_sBq9zwxWOb8JOzdPLwxrPU9s3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});